#!/usr/bin/env python3
"""Regenerate the Packages table in README.md from the tap's formulae and casks.

Scans ``Formula/*.rb`` and ``Casks/*.rb`` for each item's ``desc`` and
``homepage``, then rewrites the table between the ``BEGIN/END PACKAGES TABLE``
markers in README.md. A package that ships as both a formula and a cask is
listed once with a combined type.

Standard library only. Run with no arguments to rewrite README.md in place, or
with ``--check`` to fail (non-zero exit) when the table is stale — used in CI so
adding a formula without regenerating the table is caught in review.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = REPO / "README.md"

BEGIN = "<!-- BEGIN PACKAGES TABLE (generated by scripts/gen_readme_packages.py — do not edit by hand) -->"
END = "<!-- END PACKAGES TABLE -->"

_FIELD = {
    "desc": re.compile(r'^\s*desc\s+"((?:[^"\\]|\\.)*)"', re.MULTILINE),
    "homepage": re.compile(r'^\s*homepage\s+"((?:[^"\\]|\\.)*)"', re.MULTILINE),
}


def field(text: str, key: str) -> str:
    """Extract a quoted Ruby field value (``desc``/``homepage``) or ``""``."""
    match = _FIELD[key].search(text)
    return match.group(1) if match else ""


def escape_cell(value: str) -> str:
    """Escape characters that would corrupt a Markdown table cell.

    A literal ``|`` in a description (e.g. a PyPI summary) would otherwise be
    read as a column delimiter, shifting every following cell and silently
    breaking the row.
    """
    return value.replace("|", "\\|")


def collect(dir_name: str) -> dict[str, dict[str, str]]:
    """Map stem -> {desc, homepage} for every ``.rb`` file in a tap subdirectory."""
    items: dict[str, dict[str, str]] = {}
    directory = REPO / dir_name
    if not directory.is_dir():
        return items
    for path in sorted(directory.glob("*.rb")):
        text = path.read_text()
        items[path.stem] = {
            "desc": field(text, "desc"),
            "homepage": field(text, "homepage"),
        }
    return items


def build_table() -> str:
    """Render the Markdown packages table (marker comments included)."""
    formulae = collect("Formula")
    casks = collect("Casks")

    rows = ["| Package | What it does | Type | Needs Python? |",
            "|---------|--------------|------|---------------|"]
    for name in sorted(formulae.keys() | casks.keys()):
        meta = formulae.get(name) or casks[name]
        in_formula, in_cask = name in formulae, name in casks
        if in_formula and in_cask:
            kind, python = "Formula + Cask", "Formula: yes / Cask: no"
        elif in_formula:
            kind, python = "Formula", "Yes"
        else:
            kind, python = "Cask", "No"
        homepage = meta["homepage"] or f"https://pypi.org/project/{name}/"
        rows.append(
            f"| [`{escape_cell(name)}`]({homepage}) | {escape_cell(meta['desc'])} "
            f"| {kind} | {python} |"
        )
    return "\n".join([BEGIN, *rows, END])


def splice(readme: str, table: str) -> str:
    """Replace the marked region of the README with a freshly built table."""
    start, end = readme.find(BEGIN), readme.find(END)
    if start == -1 or end == -1:
        sys.exit("error: BEGIN/END PACKAGES TABLE markers not found in README.md")
    return readme[:start] + table + readme[end + len(END):]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if README.md is out of date")
    args = parser.parse_args()

    current = README.read_text()
    updated = splice(current, build_table())

    if args.check:
        if current != updated:
            sys.exit("README.md packages table is stale; run "
                     "`python scripts/gen_readme_packages.py`")
        print("README.md packages table is up to date")
        return

    if current != updated:
        README.write_text(updated)
        print("Updated README.md packages table")
    else:
        print("README.md packages table already up to date")


if __name__ == "__main__":
    main()
